name: End-to-end tests cypress
on:
  push:
    branches:
      - task-269/end-to-end-tests-cypress
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 14.17.5
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.5
      - name: Build 11ty
        run: |
          mkdir dist
          npm install

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:8080