name: End to end tests
on:
  push:
    branches:
      - task-269/end-to-end-tests
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.17.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      - name: Build 11ty
        run: |
          mkdir dist
          npm install
          npm run build
          npm run test:setup

      - name: Run test
        run: |
          npm test
