name: Update static content

on:
  repository_dispatch:
  # schedule:
  #   # - cron: '35 * * * *'
  

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - name: Check for static content updates # update static content repo.
        run: |
          mkdir dist
          npm install
          npm update static-content-cannabis
      - name: Create Pull Request # https://github.com/marketplace/actions/create-pull-request
        id: cpr
        uses: peter-evans/create-pull-request@v4
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"  
      - name: Auto approve static content update changes # https://github.com/hmarr/auto-approve-action
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.ODI_GITHUB_TOKEN }}
          review-message: "Auto approved automated PR: Static content update"
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}