name: Update static content

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - name: Check for static content updates # npm-check-updates would be nice to use but not working with plain github repos.
        run: |
          mkdir dist
          npm install
          npm uninstall static-content-cannabis
          npm install static-content-cannabis --save
      - name: Create Pull Request # https://github.com/marketplace/actions/create-pull-request
        id: cpr
        uses: peter-evans/create-pull-request@v4
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"  
      - name: Auto approve static content update changes
        uses: hmarr/auto-approve-action@v2
          with:
            github-token: ${{ secrets.ODI_GITHUB_TOKEN }}
            review-message: "Auto approved automated PR: Static content update"
            pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}