name: Update static content [main]

on:
  repository_dispatch:
    types: [static_content_update_main]
  schedule:
    - cron: '35 * * * *'

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - name: Check for static content updates # update static content repo. Only install production so build goes faster.
        run: |
          mkdir dist
          # npm install --production
          npm update static-content-cannabis
      - name: Create Pull Request # https://github.com/marketplace/actions/create-pull-request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: ${{ secrets.ODI_GITHUB_USER }} <noreply@github.com> 
          base: main
          title: "Static content update to main branch from WordPress API > AWS Lambda cagov/cannabis-lambda-sync-github > cagov/static-content-cannabis"
          body: |
           Update report
          labels: |
            content-update
            automerge
          # valid inputs are ['token', 'path', 'add-paths', 'commit-message', 'committer', 'author', 'signoff', 'branch', 'delete-branch', 'branch-suffix', 'base', 'push-to-fork', 'title', 'body', 'labels', 'assignees', 'reviewers', 'team-reviewers', 'milestone', 'draft']
          commit-message: "Automated PR: Static content update"
          team-reviewers: |
            ${{ secrets.PR_REVIEWERS }}
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"  
      # - name: Auto approve static content update changes # https://github.com/hmarr/auto-approve-action
      #   uses: hmarr/auto-approve-action@v2
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
      - id: automerge
        name: Auto merge static content update
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Dispatch build workflow # merge by bot not triggering push, dispatching workflow instead
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 11ty build [production]
          token: ${{ secrets.GITHUB_TOKEN }}